# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x05proto\"S\n\x08Supplier\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0c\x63ompany_name\x18\x02 \x01(\t\x12\x16\n\x0e\x63ontact_person\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"7\n\x11SuppliersResponse\x12\"\n\tsuppliers\x18\x01 \x03(\x0b\x32\x0f.proto.Supplier\"T\n\x15\x43reateSupplierRequest\x12\x14\n\x0c\x63ompany_name\x18\x01 \x01(\t\x12\x16\n\x0e\x63ontact_person\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\"`\n\x15UpdateSupplierRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0c\x63ompany_name\x18\x02 \x01(\t\x12\x16\n\x0e\x63ontact_person\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"#\n\x15\x44\x65leteSupplierRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\x89\x02\n\x0fSupplierService\x12?\n\x0e\x43reateSupplier\x12\x1c.proto.CreateSupplierRequest\x1a\x0f.proto.Supplier\x12\x36\n\x0cGetSuppliers\x12\x0c.proto.Empty\x1a\x18.proto.SuppliersResponse\x12?\n\x0eUpdateSupplier\x12\x1c.proto.UpdateSupplierRequest\x1a\x0f.proto.Supplier\x12<\n\x0e\x44\x65leteSupplier\x12\x1c.proto.DeleteSupplierRequest\x1a\x0c.proto.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUPPLIER']._serialized_start=24
  _globals['_SUPPLIER']._serialized_end=107
  _globals['_SUPPLIERSRESPONSE']._serialized_start=109
  _globals['_SUPPLIERSRESPONSE']._serialized_end=164
  _globals['_CREATESUPPLIERREQUEST']._serialized_start=166
  _globals['_CREATESUPPLIERREQUEST']._serialized_end=250
  _globals['_UPDATESUPPLIERREQUEST']._serialized_start=252
  _globals['_UPDATESUPPLIERREQUEST']._serialized_end=348
  _globals['_DELETESUPPLIERREQUEST']._serialized_start=350
  _globals['_DELETESUPPLIERREQUEST']._serialized_end=385
  _globals['_EMPTY']._serialized_start=387
  _globals['_EMPTY']._serialized_end=394
  _globals['_SUPPLIERSERVICE']._serialized_start=397
  _globals['_SUPPLIERSERVICE']._serialized_end=662
# @@protoc_insertion_point(module_scope)
