global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
  - job_name: 'domain-service'
    static_configs:
      - targets: ['domain-service:50051']
